version: "3.8"

services:
  backend:
    build: .
    container_name: nest-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    mem_limit: 300m
    cpus: "0.5"
    env_file:
      - .env